name: CI

on:
  push:
    branches:
      - '**'   # all branches
    tags-ignore:
      - '*'    # ignore all tags
  pull_request:
    branches:
      - '**'   # all branches
jobs:
  golang-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install linter dependencies
        run: make .install-linter

      - name: Run linter
        run: make linter

      - name: Run tests
        run: make tests

  k6-build:
    runs-on: ubuntu-latest
    needs: [ golang-ci ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download dependencies
        run: go mod download

      - name: Install k6
        run: make .install-k6

      - name: Run k6 builder
        run: make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k6-artifacts
          path: build